config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get "signup" => "devise/registrations#index", as: "signup_index"
    get "/signup/registration" => "devise/registrations#new", as: "signup_registration"
    get "/signup/confirmation" => "phonenumbers#new", as: "phonenumber_registration"
    get "/signup/address/:id" => "addresses#new", as: "address_new_registration"
    post "/signup/address/:id" => "addresses#create", as: "address_create_registration"
    get "/signup/credit/:id" => "credits#new", as: "credit_new_registration"
    post "/signup/credit/:id" => "credits#create", as: "credit_create_registration"
    get "/signup/complete" => "users/registrations#complete", as: "complete_registration"
  end
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: 'users/registrations',
    sessions: 'users/sessions'
   }
  root 'tops#index'
  resources :tops, only: [:index] do
    collection do
      get 'get_child_categories', defaults: { format: 'json' }
      get 'get_grandchild_categories', defaults: { format: 'json' }
    end
  end
  resources :phonenumbers, only: [:new, :create]
  resources :users, only: [:show] do
    resources :credits, only: [:index, :create]
    collection do
      get 'card'
      get 'identification'
      get 'logout'
      get 'profile'
    end
  end
  resources :exhibitions, only: [:index, :show]
  resources :items, except: [:index] do
    collection do
      get 'search'
      get 'get_children_categories', defaults: { format: 'json' }
      get 'get_grandchildren_categories', defaults: { format: 'json' }
    end
  end
  resources :purchases, only: [:show, :update]
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  # 各アクションごとに新規インスタンスを作成します
  # 各アクションごとに、遷移元のページのデータをsessionに保管していきます
  
  def step1
    # binding.pry
    @user = User.new # 新規インスタンス作成
  end
  
  def step2
    # step1で入力された値をsessionに保存
    session[:nickname] = user_params[:nickname]
    session[:email] = user_params[:email]
    session[:password] = user_params[:password]
    session[:password_confirmation] = user_params[:password_confirmation]
    # session[:password_confirmation] = user_params[:password_confirmation]
    session[:last_name] = user_params[:last_name]
    session[:first_name] = user_params[:first_name]
    session[:last_name_kana] = user_params[:last_name_kana]
    session[:first_name_kana] = user_params[:first_name_kana]
    # session[:birthday] = user_params[:birthday]
    @user = User.new # 新規インスタンス作成
  end
  
  def step3
    # step2で入力された値をsessionに保存
    session[:phone_number] = user_params[:phone_number]
    @user = User.new # 新規インスタンス作成
    @address = Address.new
    # binding.pry
  end

  def step4
    # @address = Address.new
  end

  # def show
  # end

  def create
    # binding.pry
    @user = User.new(
      nickname: session[:nickname], # sessionに保存された値をインスタンスに渡す
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      last_name: session[:last_name],
      first_name: session[:first_name],
      last_name_kana: session[:last_name_kana],
      first_name_kana: session[:first_name_kana]
      # birthday: session[:birthday],
      # phone_number: session[:phone_number]
    )
    if @user.save
     # ログインするための情報を保管
      session[:id] = @user.id
      redirect_to step3_signup_index_path
    else
      render :new
      # binding.pry
    end
  end

  def done
    # sign_in User.find(session[:id]) unless user_signed_in?
  end

  private
  # 許可するキーを設定します

  def user_params
    params.require(:user).permit(
      :nickname,
      :email,
      :password,
      :password_confirmation,
      :last_name,
      :first_name,
      :last_name_kana,
      :first_name_kana
      # :birthday,
      # :avatar,
      # :introduction,
      # :phone_number
  )
  end
  
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/signup/done.html.haml
.registration-html
  .registration-body
    .registration-all
      .registration-all__container
        / ヘッダー部分
        %header.registration-all__header
          %h1.registration-all__header--h1
            = link_to "/", class: "registration-all__header--a" do
              = image_tag "mercari2.png"
          %nav.registration-all__bar
            %ol.registration-all__bar--ol
              %li.registration-all__bar--through
                会員情報
                .progress-status
              %li.registration-all__bar--through-through
                電話番号認証
                .progress-status
              %li.registration-all__bar--through-through
                お届け先住所入力
                .progress-status
              %li.registration-all__bar--through-through
                支払い方法
                .progress-status
              %li.registration-all__bar--active-last
                完了
                .progress-status
        / メイン部分
        %main.registration-all__main
          %section.registration-all__main-container
            %h2.registration-all__chapter-head 会員登録完了
            %form.registration-all__inner{:action => "/"}
              .registration-all__content
                %p.sucsess
                  ありがとうございます。
                  %br
                  会員登録が完了しました。
                %button.registration-all__btn-red{:type => "submit"}
                  メルカリをはじめる

        / フッター部分
        = render 'shared/footer'

app/views/signup/index.html.haml
.new-user-top
  .new-user-top__container

    -# ヘッダー部分
    = render "shared/header"
    
    -# メイン部分
    %main.new-user-top-main
      %section.new-user-top-main__container
        %h2.new-user-top-main__container__logo
          新規会員登録


        .new-user-top-main__container__inners
          .new-user-top-main__container__inners__inner
            = link_to step1_signup_index_path, class: "new-user-top-main__container__inners__inner--btn-mail" do
              %i.fa.fa-envelope
              メールアドレスで登録する
            %button.new-user-top-main__container__inners__inner__btn-sns
              %i.fab.fa-facebook-square
              Facebookで登録する
            %button.new-user-top-main__container__inners__inner__btn-sns-google
              = image_tag "googleLogo.jpg"
              Googleで登録する
    
    -# フッター部分
    = render 'shared/footer'

app/views/signup/step1.html.haml
.registration-html
  .registration-body
    .registration-all
      .registration-all__container
        / ヘッダー部分
        %header.registration-all__header
          %h1.registration-all__header--h1
            = link_to "/", class: "registration-all__header--a" do
              = image_tag "mercari2.png"
          %nav.registration-all__bar
            %ol.registration-all__bar--ol
              %li.registration-all__bar--active-first
                会員情報
                .progress-status
              %li.registration-all__bar--li
                電話番号認証
                .progress-status
              %li.registration-all__bar--li
                お届け先住所入力
                .progress-status
              %li.registration-all__bar--li
                支払い方法
                .progress-status
              %li.registration-all__bar--last
                完了
                .progress-status
        / メイン部分
        %main.registration-all__main
          %section.registration-all__main-container
          %h2.registration-all__single-head 会員情報入力
          -# = form_with model: @user, url: step2_signup_index_path, method: :get, local: true, class: "registration_form" do |f|
          = form_for @user, url: step2_signup_index_path, method: :get do |f|
            %form.registration-all__inner
              .registration-all__content
                .registration-all__form-group
                  %label.registration-all__form-group--label{for: "nickname"} ニックネーム
                  %span.registration-all__require 必須
                  = f.text_field(:nickname, class: "input-default", placeholder: "例）メルカリ太郎")
                  -# %input.input-default{:placeholder => "例）メルカリ太郎", :type => "text"}
                .registration-all__form-group
                  %label.registration-all__form-group--label{for: "email"} メールアドレス
                  %span.registration-all__require 必須
                  = f.email_field(:email, class: "input-default", placeholder: "PC・携帯どちらでも可")
                  -# %input.input-default{:placeholder => "PC・携帯どちらでも可", :type => "email"}/
                .registration-all__form-group
                  %label.registration-all__form-group--label{for: "password"} パスワード
                  %span.registration-all__require 必須
                  = f.password_field(:password, class: "input-default", placeholder: "6文字以上")
                  -# %input.input-default{:placeholder => "6文字以上", :type => "password"}/
                .registration-all__form-group
                  %label.registration-all__form-group--label{for: "password_confirmation"} パスワード（確認）
                  %span.registration-all__require 必須
                  = f.password_field(:password_confirmation, class: "input-default", placeholder: "6文字以上")
                  -# %input.input-default{:placeholder => "6文字以上", :type => "password"}/
                .registration-all__form-group
                  %h3.registration-all__sub-head 本人確認
                  %p.registration-all__content--text
                    安心・安全にご利用いただくために、お客様の本人情報の登録に
                    ご協力ください。他のお客さまに公開されることはありません。
                .registration-all__form-group
                  %div
                    %label.registration-all__form-group--label お名前(全角)
                    %span.registration-all__require 必須
                  = f.text_field(:last_name, class: "input-default harf", placeholder: "例）山田")
                  -# %input.input-default.harf{:placeholder => "例）山田", :type => "text"}/
                  = f.text_field(:first_name, class: "input-default harf", placeholder: "例）彩")
                  -# %input.input-default.harf{:placeholder => "例）彩", :type => "text"}/
                .registration-all__form-group
                  %div
                    %label.registration-all__form-group--label お名前カナ(全角)
                    %span.registration-all__require 必須
                  = f.text_field(:last_name_kana, class: "input-default harf", placeholder: "例）ヤマダ")
                  -# %input.input-default.harf{:placeholder => "例）ヤマダ", :type => "text"}/
                  = f.text_field(:first_name_kana, class: "input-default harf", placeholder: "例）アヤ")
                  -# %input.input-default.harf{:placeholder => "例）アヤ", :type => "text"}/
                .registration-all__form-group
                  %label.registration-all__form-group--label{"for-": "birthday"} 生年月日
                  %span.registration-all__require 必須
                  .registration-all__birthday-select
                    .registration-all__birthday-select__select
                      %i.fa.fa-chevron-down
                      %select.registration-all__birthday-select__select--default
                        %option{value: ""} --
                        -i = 2019
                        = while i >= 1900
                          %option{value: "#{i}"} #{i}
                          -i -= 1
                    %span 年
                    .registration-all__birthday-select__select
                      %i.fa.fa-chevron-down
                      %select.registration-all__birthday-select__select--default
                        %option{value: ""} --
                        - for i in 01..12
                          %option{value: "#{i}"} #{i}
                    %span 月
                    .registration-all__birthday-select__select
                      %i.fa.fa-chevron-down
                      %select.registration-all__birthday-select__select--default
                        %option{value: ""} --
                        - for i in 01..31
                          %option{value: "#{i}"} #{i}
                    %span 日
                  %p.registration-all__content--text-gray
                    ※ 本人情報は正しく入力してください。会員登録後、修正するには
                    お時間を頂く場合があります。
                    = render "shared/recaptcha"
                  .registration-all__form-group
                    %p.registration-all__content--text-center
                      「次へ進む」のボタンを押すことにより、
                      = link_to "利用規約", "/", class: "registration-all__a"
                      に同意したものとみなします
                  %button.registration-all__btn-red{type: "submit"}
                    次へ進む
                  .registration-all__form-group
                    %p.text-right
                      = link_to "本人情報の登録について", "/", class: "registration-all__a"
                      %i.fas.fa-chevron-right


      / フッター部分
      = render 'shared/footer'

app/views/signup/step2.html.haml
.registration-html
  .registration-body
    .registration-all
      .registration-all__container
        / ヘッダー部分
        %header.registration-all__header
          %h1.registration-all__header--h1
            = link_to "/", class: "registration-all__header--a" do
              = image_tag "mercari2.png"
          %nav.registration-all__bar
            %ol.registration-all__bar--ol
              %li.registration-all__bar--through
                会員情報
                .progress-status
              %li.registration-all__bar--active
                電話番号認証
                .progress-status
              %li.registration-all__bar--li
                お届け先住所入力
                .progress-status
              %li.registration-all__bar--li
                支払い方法
                .progress-status
              %li.registration-all__bar--last
                完了
                .progress-status
        / メイン部分
        %main.registration-all__main
          %section.registration-all__main-container
            %h2.registration-all__chapter-head 電話番号の確認
            -# = form_with model: @user, url: signup_index_path, method: :post, local: true, class: "registration-all__inner" do |f|
            -# = form_for @user, url: step3_signup_index_path, method: :get do |f|
            = form_for @user, url: create_signup_index_path, method: :post do |f|
              .registration-all__content
                .registration-all__form-group
                  %label.registration-all__form-group--label 携帯電話の番号
                  = f.text_field(:phone_number, class: "input-default", placeholder: "携帯電話の番号を入力", type: "tel")
                  -# %input.input-default{:placeholder => "携帯電話の番号を入力", :type => "tel"}/
                %p.registration-all__content--text
                  本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して
                  認証を行います。
                  = f.submit "SMSを送信する", class: "registration-all__btn-red"
                %p.registration-all__content--text
                  ※電話番号は本人確認や不正利用防止のために利用します。
                  他のユーザーに公開されることはありません。
                .registration-all__form-group
                  %p.text-right
                    = link_to "電話番号の確認が必要な理由", "/", class: "registration-all__a"
                    %i.fas.fa-chevron-right

        / フッター部分
        = render 'shared/footer'

app/views/signup/step3.html.haml
.registration-html
  .registration-body
    .registration-all
      .registration-all__container
        / ヘッダー部分
        %header.registration-all__header
          %h1.registration-all__header--h1
            = link_to "/", class: "registration-all__header--a" do
              = image_tag "mercari2.png"
          %nav.registration-all__bar
            %ol.registration-all__bar--ol
              %li.registration-all__bar--through
                会員情報
                .progress-status
              %li.registration-all__bar--through-through
                電話番号認証
                .progress-status
              %li.registration-all__bar--active
                お届け先住所入力
                .progress-status
              %li.registration-all__bar--li
                支払い方法
                .progress-status
              %li.registration-all__bar--last
                完了
                .progress-status
        / メイン部分
        %main.registration-all__main
          %section.registration-all__main-container
            %h2.registration-all__chapter-head 住所入力
            = form_for @address, url: step4_signup_index_path, method: :get do |f|
              .registration-all__content
                .registration-all__form-group
                  %div
                    %label.registration-all__form-group--label お名前(全角)
                    %span.registration-all__require 必須
                  = f.text_field(:last_name, class: "input-default harf", placeholder: "例）山田", :type => "text")
                  -# %input.input-default.harf{:placeholder => "例）山田", :type => "text"}/
                  = f.text_field(:last_name, class: "input-default harf", placeholder: "例）彩", :type => "text")
                  -# %input.input-default.harf{:placeholZder => "例）彩", :type => "text"}/
                .registration-all__form-group
                  %div
                    %label.registration-all__form-group--label  お名前カナ(全角)
                    %span.registration-all__require 必須
                  = f.text_field(:last_name, class: "input-default harf", placeholder: "例）ヤマダ", :type => "text")
                  -# %input.input-default.harf{:placeholder => "例）ヤマダ", :type => "text"}/
                  = f.text_field(:last_name, class: "input-default harf", placeholder: "例）アヤ", :type => "text")
                  -# %input.input-default.harf{:placeholder => "例）アヤ", :type => "text"}/
                .registration-all__form-group
                  %label.registration-all__form-group--label{for: "zip-code"} 郵便番号
                  %span.registration-all__require 必須
                  = f.text_field(:postal_cord, class: "input-default", placeholder: "例）123-4567", type: "text")
                  -# %input.input-default{:placeholder => "例）123-4567", :type => "text"}/
                .registration-all__form-group
                  %label.registration-all__form-group--label{for: "prefecture"} 都道府県
                  %span.registration-all__require 任意
                  .registration-all__form-group__wrap
                    %i.fa.fa-chevron-down
                    %select.select-default{name: "prefecture", placeholder: "Source Type"}
                      %option{value: ""} ---
                      - Prefecture.all.each do |ele|
                        %option{value: ele.name}= ele.name
                .registration-all__form-group
                  %label.registration-all__form-group--label{for: "city"} 市区町村
                  %span.registration-all__require 必須
                  = f.text_field(:municipalities, class: "input-default", placeholder: "例）横浜市緑区", type: "text")
                  -# %input.input-default{:placeholder => "例）横浜市緑区", :type => "text"}/
                .registration-all__form-group
                  %label.registration-all__form-group--label{:for => "street-num"} 番地
                  %span.registration-all__require 必須
                  = f.text_field(:house_number, class: "input-default", placeholder: "例）青山1-1-1", type: "text")
                  -# %input.input-default{:placeholder => "例）青山1-1-1", :type => "text"}/
                .registration-all__form-group
                  %label.registration-all__form-group--label{:for => "buil"} 建物名
                  %span.registration-all__require.gray 任意
                  = f.text_field(:building_name, class: "input-default", placeholder: "例）柳ビル103", type: "text")
                  -# %input.input-default{:placeholder => "例）柳ビル103", :type => "text"}/
                .registration-all__form-group
                  %label.registration-all__form-group--label{:for => "tel"} 電話
                  %span.registration-all__require.gray 任意
                  = f.text_field(:phone_number, class: "input-default", placeholder: "例）09012345678", type: "tel")
                  -# %input.input-default{:placeholder => "例）09012345678", :type => "tel"}/
                %button.registration-all__btn-red{:type => "submit"}
                  次へ進む

        / フッター部分
        = render 'shared/footer'

app/views/signup/step4.html.haml
.registration-html
  .registration-body
    .registration-all
      .registration-all__container
        / ヘッダー部分
        %header.registration-all__header
          %h1.registration-all__header--h1
            = link_to "/", class: "registration-all__header--a" do
              = image_tag "mercari2.png"
          %nav.registration-all__bar
            %ol.registration-all__bar--ol
              %li.registration-all__bar--through
                会員情報
                .progress-status
              %li.registration-all__bar--through-through
                電話番号認証
                .progress-status
              %li.registration-all__bar--through-through
                お届け先住所入力
                .progress-status
              %li.registration-all__bar--active
                支払い方法
                .progress-status
              %li.registration-all__bar--last
                完了
                .progress-status
        / メイン部分
        %main.registration-all__main
          %section.registration-all__main-container
            %h2.registration-all__chapter-head 支払い方法
            %form.registration-all__inner{:action => "/signup/done"}
              .registration-all__content
                .registration-all__form-group
                  %label.registration-all__form-group--label{:for => "card-num"} カード番号
                  %span.registration-all__require 必須
                  %input.input-default{:placeholder => "半角数字のみ", :type => "text"}/

                  %ul.registration-all__cards
                    %li.registration-all__cards--card
                      = image_tag "visa.png"
                    %li.registration-all__cards--card
                      = image_tag "mastercard.png"
                    %li.registration-all__cards--card
                      = image_tag "saison-card.png"
                    %li.registration-all__cards--card
                      = image_tag "jcb.png"
                    %li.registration-all__cards--card
                      = image_tag "american_express.png"
                    %li.registration-all__cards--card
                      = image_tag "dinersclub.png"
                    %li.registration-all__cards--card
                      = image_tag "discover.png"

                .registration-all__form-group
                  %div
                    %label.registration-all__form-group--label 有効期限
                    %span.registration-all__require 必須
                  %select.input-default.half.card
                    %option{:value => "1"} 01
                    %option{:value => "2"} 02
                    %option{:value => "3"} 03
                    %option{:value => "4"} 04
                    %option{:value => "5"} 05
                    %option{:value => "6"} 06
                    %option{:value => "7"} 07
                    %option{:value => "8"} 08
                    %option{:value => "9"} 09
                    %option{:value => "10"} 10
                    %option{:value => "11"} 11
                    %option{:value => "12"} 12
                  %span.month 月
                  %select.input-default.half.card
                    - for i in 19..29
                      %option{:value => "#{i}"} #{i}
                  %span.year 年
                .registration-all__form-group
                  %label.registration-all__form-group--label{:for => "code"} セキュリティコード
                  %span.registration-all__require 必須
                  %input.input-default{:placeholder => "カード背面4桁もしくは3桁の番号"}/
                .registration-all__form-group
                  %p.text-right
                    = link_to "カード裏面の番号とは？", "/", class: "registration-all__a"
                    %i.fas.fa-chevron-right
                %button.registration-all__btn-red{:type => "submit"}
                  次へ進む

        / フッター部分
        = render 'shared/footer'