config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get "signup" => "devise/registrations#index", as: "signup_index"
    get "/signup/registration" => "devise/registrations#new", as: "signup_registration"
    get "/signup/confirmation" => "phonenumbers#new", as: "phonenumber_registration"
    get "/signup/address/:id" => "addresses#new", as: "address_new_registration"
    post "/signup/address/:id" => "addresses#create", as: "address_create_registration"
    get "/signup/credit/:id" => "credits#new", as: "credit_new_registration"
    post "/signup/credit/:id" => "credits#create", as: "credit_create_registration"
    get "/signup/complete" => "users/registrations#complete", as: "complete_registration"
  end
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: 'users/registrations',
    sessions: 'users/sessions'
   }
  root 'tops#index'
  resources :tops, only: [:index] do
    collection do
      get 'get_child_categories', defaults: { format: 'json' }
      get 'get_grandchild_categories', defaults: { format: 'json' }
    end
  end
  resources :phonenumbers, only: [:new, :create]
  resources :users, only: [:show] do
    resources :credits, only: [:index, :create]
    collection do
      get 'card'
      get 'identification'
      get 'logout'
      get 'profile'
    end
  end
  resources :exhibitions, only: [:index, :show]
  resources :items, except: [:index] do
    collection do
      get 'search'
      get 'get_children_categories', defaults: { format: 'json' }
      get 'get_grandchildren_categories', defaults: { format: 'json' }
    end
  end
  resources :purchases, only: [:show, :update]
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, confirmation: true

  with_options presence: true do
    validates :nickname
    validates :first_name
    validates :first_name_kana
    validates :last_name
    validates :last_name_kana
  end

  has_many :comments
  has_one :credit
  has_many :sns_credentials, dependent: :destroy



  devise :omniauthable,omniauth_providers: [:facebook, :google_oauth2]

  def self.from_omniauth(auth)
    user = User.find_by(email: auth.info.email)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first
    if sns == nil && user == nil
      @user = User.new(
        nickname: auth.info.name,
        first_name: "",
        first_name_kana: "",
        last_name: "",
        last_name_kana: "",
        email: auth.info.email,
        password: Devise.friendly_token[0,20]
        )
      @user.save(validate: false)
      @sns = SnsCredential.create(
        user_id: @user.id,
        provider: auth.provider,
        uid: auth.uid
        )
      @user = User.find(@sns.user_id)
    elsif sns == nil && user
      @user = User.find_by(email: auth.info.email)
      @sns = SnsCredential.create(
        user_id: @user.id,
        provider: auth.provider,
        uid: auth.uid
        )
    else
      @user = User.find(sns.user_id)
    end
    @user
  end
  has_many :buyer_items, foreign_key: "buyer_id", class_name: "Item"
  has_many :saling_items, -> { where("buyer_id is NULL")}, foreign_key: "seller_id", class_name: "Item"
  has_many :sold_items, -> { where("buyer_id is NULL")}, foreign_key: "seller_id", class_name: "Item"
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_for(:facebook)
  end

  
  def google_oauth2
    callback_for(:google)
  end

 

  def callback_for(provider)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #after_sign_in_path_forと同じパス
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to signup_registration_path
    end
  end

  def failure
    redirect_to root_path and return
  end
end
  

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end
  def new
    super
  end

  # POST /resource
  def create
    # @user = User.new(user_params)
    # if @user.save 
    # else
    #   render :new
    # end
    super
  end

  def complete
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  def after_sign_up_path_for(resource)
    phonenumber_registration_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   binding.pry
  #   phonenumber_registration_path
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def callback
    auth = request.env['omniauth.auth']
 
    # auth情報を元にユーザをDB登録
    # sessionにユーザIDを保持 # デバッグ用
 
    redirect_to root_path
  end
 
  def destroy
    reset_session
    redirect_to root_path
  end
 
  def failure
    redirect_to root_path
  end

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def logout
  end

  def show
  end

  def profile
  end

  def identification
  end

  def card
  end

  private

  # def redirect_root
  #   if @user.id != current_user.id
  #     redirect_to root_path
  #   end
  # end

end

app/views/users/addCard.html.haml
.mainbody
  = render "shared/top-header"
  - breadcrumb :addCard
  = render 'shared/pankuzu'
  .mainbody__main
    .mainbody__content
      %section.mainbody__container
        %h2.mainbody__chapter-head クレジットカード情報入力
        %form.mainbody__inner-registration
          .mainbody__inner-registration__single-content
            .mainbody__form-group
              %label.mainbody__form-group--label{for: :cardNum} カード番号
              %span.mainbody__require 必須
              %input.mainbody__form-group--input-default{placeholder: :半角数字のみ, type: :text}/

              %ul.mainbody__cards
                %li.mainbody__cards--card
                  = image_tag "visa.png"
                %li.mainbody__cards--card
                  = image_tag "mastercard.png"
                %li.mainbody__cards--card
                  = image_tag "saison-card.png"
                %li.mainbody__cards--card
                  = image_tag "jcb.png"
                %li.mainbody__cards--card
                  = image_tag "american_express.png"
                %li.mainbody__cards--card
                  = image_tag "dinersclub.png"
                %li.mainbody__cards--card
                  = image_tag "discover.png"

            .mainbody__form-expire
              %div
                %label.mainbody__form-group--label 有効期限
                %span.mainbody__require 必須
              .mainbody__form-expire__half
                %select.mainbody__form-expire__half--default
                  %option{value: :"1"} 01
                  %option{value: :"2"} 02
                  %option{value: :"3"} 03
                  %option{value: :"4"} 04
                  %option{value: :"5"} 05
                  %option{value: :"6"} 06
                  %option{value: :"7"} 07
                  %option{value: :"8"} 08
                  %option{value: :"9"} 09
                  %option{value: :"10"} 10
                  %option{value: :"11"} 11
                  %option{value: :"12"} 12
                %span.month 月
              .mainbody__form-expire__half
                %select.mainbody__form-expire__half--default
                  - for i in 19..29
                    %option{value: :"{#i}" } #{i}
                %span.year 年

            .mainbody__form-group-under
              %label.mainbody__form-group--label{for: :code} セキュリティコード
              %span.mainbody__require 必須
              %input.mainbody__form-group--input-default{placeholder: :カード背面4桁もしくは3桁の番号}/

            .mainbody__seqcode
              .mainbody__seqcode-text
                カード裏面の番号とは？
            %button.registration-all__btn-red{type: :submit}
              追加する

    = render 'shared/mypage-leftside'
    .mainbody__main__side
  = render "shared/top-footer"
  = render "shared/sell-button"

app/views/users/address.html.haml
.registration-html
  .registration-body
    .registration-all
      .registration-all__container
        / ヘッダー部分
        %header.registration-all__header
          %h1.registration-all__header--h1
            = link_to "/", class: "registration-all__header--a" do
              = image_tag "mercari2.png"
          %nav.registration-all__bar
            %ol.registration-all__bar--ol
              %li.registration-all__bar--through
                会員情報
                .progress-status
              %li.registration-all__bar--through-through
                電話番号認証
                .progress-status
              %li.registration-all__bar--active
                お届け先住所入力
                .progress-status
              %li.registration-all__bar--li
                支払い方法
                .progress-status
              %li.registration-all__bar--last
                完了
                .progress-status
        / メイン部分
        %main.registration-all__main
          %section.registration-all__main-container
            %h2.registration-all__chapter-head 住所入力
            %form.registration-all__inner{:action => "/users/credit"}
              .registration-all__content
                .registration-all__form-group
                  %div
                    %label.registration-all__form-group--label お名前(全角)
                    %span.registration-all__require 必須
                  %input.input-default.harf{:placeholder => "例）山田", :type => "text"}/
                  %input.input-default.harf{:placeholder => "例）彩", :type => "text"}/
                .registration-all__form-group
                  %div
                    %label.registration-all__form-group--label  お名前カナ(全角)
                    %span.registration-all__require 必須
                  %input.input-default.harf{:placeholder => "例）ヤマダ", :type => "text"}/
                  %input.input-default.harf{:placeholder => "例）アヤ", :type => "text"}/
                .registration-all__form-group
                  %label.registration-all__form-group--label{:for => "zip-code"} 郵便番号
                  %span.registration-all__require 必須
                  %input.input-default{:placeholder => "例）123-4567", :type => "text"}/
                .registration-all__form-group
                  %label.registration-all__form-group--label{:for => "state"} 都道府県
                  %span.registration-all__require 必須
                  %select.registration-all__state.input-default
                    %option{value: ""} ---
                    - Prefecture.all.each do |ele|
                      %option{value: ele.name}= ele.name
                .registration-all__form-group
                  %label.registration-all__form-group--label{:for => "city"} 市区町村
                  %span.registration-all__require 必須
                  %input.input-default{:placeholder => "例）横浜市緑区", :type => "text"}/
                .registration-all__form-group
                  %label.registration-all__form-group--label{:for => "street-num"} 番地
                  %span.registration-all__require 必須
                  %input.input-default{:placeholder => "例）青山1-1-1", :type => "text"}/
                .registration-all__form-group
                  %label.registration-all__form-group--label{:for => "buil"} 建物名
                  %span.registration-all__require.gray 任意
                  %input.input-default{:placeholder => "例）柳ビル103", :type => "text"}/
                .registration-all__form-group
                  %label.registration-all__form-group--label{:for => "tel"} 電話
                  %span.registration-all__require.gray 任意
                  %input.input-default{:placeholder => "例）09012345678", :type => "tel"}/
                %button.registration-all__btn-red{:type => "submit"}
                  次へ進む

        / フッター部分
        = render 'shared/footer'

app/views/users/card.html.haml
.mainbody
  = render 'shared/top-header'
  - breadcrumb :card
  = render 'shared/pankuzu'
  .mainbody__main
    .mainbody__content
      %section.mainbody__container
        %h2.mainbody__chapter-head 支払い方法
        .mainbody__inner
          %section.mainbody__section
            .mainbody__single-content
              %h3.mainbody__sub-head クレジットカード一覧

          %section.mainbody__add-card
            .mainbody__single-content
              = link_to user_credits_path(current_user), method: :get, class: "mainbody__btn-red" do
                %i.far.fa-credit-card
                クレジットカードを追加する

          .mainbody__text-right
            = link_to root_path, class: "mainbody__text-right--a" do
              %span 支払い方法について
              %i.fas.fa-chevron-right

    = render 'shared/mypage-leftside'
  = render 'shared/top-footer'
  = render 'shared/sell-button'

app/views/users/confirmation.html.haml
.registration-html
  .registration-body
    .registration-all
      .registration-all__container
        / ヘッダー部分
        %header.registration-all__header
          %h1.registration-all__header--h1
            = link_to "/", class: "registration-all__header--a" do
              = image_tag "mercari2.png"
          %nav.registration-all__bar
            %ol.registration-all__bar--ol
              %li.registration-all__bar--through
                会員情報
                .progress-status
              %li.registration-all__bar--active
                電話番号認証
                .progress-status
              %li.registration-all__bar--li
                お届け先住所入力
                .progress-status
              %li.registration-all__bar--li
                支払い方法
                .progress-status
              %li.registration-all__bar--last
                完了
                .progress-status
        / メイン部分
        %main.registration-all__main
          %section.registration-all__main-container
            %h2.registration-all__chapter-head 電話番号の確認
            %form.registration-all__inner{action: "/users/address"}
              .registration-all__content
                .registration-all__form-group
                  %label.registration-all__form-group--label 携帯電話の番号
                  %input.input-default{:placeholder => "携帯電話の番号を入力", :type => "tel"}/
                %p.registration-all__content--text
                  本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して
                  認証を行います。
                %button.registration-all__btn-red{:type => "submit"}
                  SMSを送信する
                %p.registration-all__content--text
                  ※電話番号は本人確認や不正利用防止のために利用します。
                  他のユーザーに公開されることはありません。
                .registration-all__form-group
                  %p.text-right
                    = link_to "電話番号の確認が必要な理由", "/", class: "registration-all__a"
                    %i.fas.fa-chevron-right

        / フッター部分
        = render 'shared/footer'

app/views/users/destroy.html.haml
.user-logput-page
  = render "shared/top-header"
  .mainbody
    = render 'shared/pankuzu'
    .mainbody__main
      .mainbody__main__contents
        .mainbody__main__contents__content
          .mainbody__main__contents__content__form
            -# .mainbody__main__contents__content__form__btn ログアウト
            = link_to destroy_user_session_path(current_user), method: :delete, class: "mainbody__main__contents__content__form--btn" do
              ログアウト
      = render 'shared/mypage-leftside'
      .mainbody__main__side
  = render "shared/top-footer"
  = render "shared/sell-button"

app/views/users/exhibiting.html.haml
.mainbody
  = render 'shared/top-header'
  - breadcrumb :exhibiting
  = render 'shared/pankuzu'
  .mainbody__main
    .mainbody__content
      %section.mainbody__container.exhibiting-page
        %h2.exhibiting-page__head 出品した商品
        %ul.exhibiting-page__listing-tabs
          %li.active
            %h3 出品中
          %li
            %h3 取引中
          %li
            %h3 売却済み
        %ul.exhibiting-page__content
          - if @selling_items.present?
            - @selling_items.each do |item|
              %li.exhibiting-page__content__list
                = link_to edit_item_path(item), class: "item-list" do
                  .item-list__image
                    = image_tag item.images[0].variant(resize: '48x48'), width:"48", height:"48", alt: "イメージ1"
                  .item-list__body
                    .item-list__body__text
                      = item.name
                    .item-list__body__under
                      %span.item-list__body__under__wrapper
                        %i.far.fa-heart.item-list__body--under__wrapper--icon 
                        %span.item-list__body--under__wrapper--number 4
                      %span.item-list__body__under__wrapper
                        %i.far.fa-comment.item-list__body--under__wrapper--icon
                        %span.item-list__body--under__wrapper--number 0
                      .item-list__body__under--status
                        出品中
                  .item-list__arrow
                    %i.fa.fa-chevron-right
          - else
            取引中の商品がありません
      %ul.exhibiting-page__pager
        %li.exhibiting-page__pager__cell.prev-page
          %i.fa.fa-chevron-left
        %li.exhibiting-page__pager__cell.next-page
          %i.fa.fa-chevron-right

    = render 'shared/mypage-leftside'
  = render 'shared/top-footer'
  = render 'shared/sell-button'

app/views/users/identification.html.haml
.user_identification_page
  = render 'shared/top-header'
  - breadcrumb :identification
  = render 'shared/pankuzu'
  .zentai.clearfix
    .zentai__identification
      .zentai__identification__header
        %h2.zentai__identification__header__head 本人情報の登録
        %form.zentai__identification__header__inner{action: "https://www.mercari.com/jp/mypage/identification/save/", method: "POST", novalidate: ""}
          %div
            %p
              お客さまの本人情報をご登録ください。
              %br>/
              登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
            %p.text-right
              =link_to "本人確認書類のアップロードについて", href: "/jp/help_center/article/495/", target: "_blank"
              %i.fa.fa-chevron-right
          .zentai__identification__header__form-group
            %label お名前
            .zentai__identification__header__form-group__p
              %p= current_user.last_name
              &nbsp;
              %p= current_user.first_name
          .zentai__identification__header__form-group
            %label お名前カナ
            .zentai__identification__header__form-group__p
              %p= current_user.last_name_kana
              &nbsp;
              %p= current_user.first_name_kana
          .zentai__identification__header__form-group
            %label{:for => "birthday"} 生年月日
            - if current_user.birthday.present?
              %p= current_user.birthday.strftime("%Y/%m/%d")
            - else
              %p 未設定
          .zentai__identification__header__form-group
            %label{:for => "zip_code"} 郵便番号
            %span.form-arbitrary 任意
            %input.input-default{name: "zip_code", placeholder: "例）1234567", type: "text", value: ""}/
          .zentai__identification__header__form-group
            %label{for: "prefecture"} 都道府県
            %span.form-arbitrary 任意
            .zentai__identification__header__form-group__wrap
              %i.fa.fa-chevron-down
              %select.select-default{name: "prefecture", placeholder: "Source Type"}
                %option{value: ""} ---
                - Prefecture.all.each do |ele|
                  %option{value: ele.name}= ele.name
          .zentai__identification__header__form-group
            %label{for: "city"} 市区町村
            %span.form-arbitrary 任意
            %input.input-default{name: "city", placeholder: "例) 横浜市緑区", type: "text", value: ""}/
          .zentai__identification__header__form-group
            %label{for: "address1_label"} 番地
            %span.form-arbitrary 任意
            %input.input-default{name: "address1", placeholder: "例) 青山1−1−1", type: "text", value: ""}/
          .zentai__identification__header__form-group
            %label{:for => "address2_label"} 建物名
            %span.form-arbitrary 任意
            %input.input-default{name: "address2", placeholder: "例) 柳ビル103", type: "text", value: ""}/
          %button.btn-default.btn-red{type: "submit"} 登録する
          .zentai__identification__header__form-group.text-right
            %p
              =link_to "本人情報の登録について", "/jp/help_center/article/423/", target: "_blank"
              %i.fa.fa-chevron-right
          %input{name: "__csrf_value", type: "hidden", value: "4fe50019f8a35515078af98e33124f88f26c4a8f12e3ad25e083544b81ee79b1e60d44039b0a1c9518ad73c79f44a4cb318b2e09081084c822b2318582a46b5f0"}/

    = render 'shared/mypage-leftside'
  = render 'shared/top-footer'
  = render 'shared/sell-button'

app/views/users/registration.html.haml
.registration-html
  .registration-body
    .registration-all
      .registration-all__container
        / ヘッダー部分
        %header.registration-all__header
          %h1.registration-all__header--h1
            = link_to "/", class: "registration-all__header--a" do
              = image_tag "mercari2.png"
          %nav.registration-all__bar
            %ol.registration-all__bar--ol
              %li.registration-all__bar--active-first
                会員情報
                .progress-status
              %li.registration-all__bar--li
                電話番号認証
                .progress-status
              %li.registration-all__bar--li
                お届け先住所入力
                .progress-status
              %li.registration-all__bar--li
                支払い方法
                .progress-status
              %li.registration-all__bar--last
                完了
                .progress-status
        / メイン部分
        %main.registration-all__main
          %section.registration-all__main-container
            %h2.registration-all__single-head 会員情報入力
            -# = form_with resource, as: resource_name, url: registration_path(resource_name) do |f|
            = form_with(model: @users, url: users_confirmation_path, method: :get, local: true) do |f|
              .registration-all__inner
                .registration-all__content
                  .registration-all__form-group
                    %label.registration-all__form-group--label{for: "nickname"} ニックネーム
                    %span.registration-all__require 必須
                    = f.text_field(:nickname, class: "input-default", placeholder: "例）メルカリ太郎")
                    -# %input.input-default{:placeholder => "例）メルカリ太郎", :type => "text"}
                  .registration-all__form-group
                    %label.registration-all__form-group--label{:for => "email"} メールアドレス
                    %span.registration-all__require 必須
                    = f.email_field(:email, class: "input-default", placeholder: "PC・携帯どちらでも可")
                    -# %input.input-default{:placeholder => "PC・携帯どちらでも可", :type => "email"}/
                  .registration-all__form-group
                    %label.registration-all__form-group--label{:for => "password"} パスワード
                    %span.registration-all__require 必須
                    = f.password_field(:password, class: "input-default", placeholder: "6文字以上")
                    -# %input.input-default{:placeholder => "6文字以上", :type => "password"}/
                  .registration-all__form-group
                    %label.registration-all__form-group--label{:for => "password"} パスワード（確認）
                    %span.registration-all__require 必須
                    = f.password_field(:password, class: "input-default", placeholder: "6文字以上")
                    -# %input.input-default{:placeholder => "6文字以上", :type => "password"}/
                  .registration-all__form-group
                    %h3.registration-all__sub-head 本人確認
                    %p.registration-all__content--text
                      安心・安全にご利用いただくために、お客様の本人情報の登録に
                      ご協力ください。他のお客さまに公開されることはありません。
                  .registration-all__form-group
                    %div
                      %label.registration-all__form-group--label お名前(全角)
                      %span.registration-all__require 必須
                    = f.text_field(:last_name, class: "input-default harf", placeholder: "例）山田")
                    -# %input.input-default.harf{:placeholder => "例）山田", :type => "text"}/
                    = f.text_field(:first_name, class: "input-default harf", placeholder: "例）彩")
                    -# %input.input-default.harf{:placeholder => "例）彩", :type => "text"}/
                  .registration-all__form-group
                    %div
                      %label.registration-all__form-group--label お名前カナ(全角)
                      %span.registration-all__require 必須
                    = f.text_field(:first_name, class: "input-default harf", placeholder: "例）ヤマダ")
                    -# %input.input-default.harf{:placeholder => "例）ヤマダ", :type => "text"}/
                    = f.text_field(:first_name, class: "input-default harf", placeholder: "例）アヤ")
                    -# %input.input-default.harf{:placeholder => "例）アヤ", :type => "text"}/
                  .registration-all__form-group
                    %label.registration-all__form-group--label{"for-" => "birthday"} 生年月日
                    %span.registration-all__require 必須
                    .registration-all__birthday-select
                      .registration-all__birthday-select__select
                        %i.icon-arrow-bottom
                        %select.registration-all__birthday-select__select--default
                          %option{:value => ""} --
                          -i = 2019
                          = while i >= 1900
                            %option{:value => "#{i}"} #{i}
                            -i -= 1
                      %span 年
                      .registration-all__birthday-select__select
                        %i.icon-arrow-bottom
                        %select.registration-all__birthday-select__select--default
                          %option{value: ""} --
                          - for i in 01..12
                            %option{value: "#{i}"} #{i}
                      %span 月
                      .registration-all__birthday-select__select
                        %i.icon-arrow-bottom
                        %select.registration-all__birthday-select__select--default
                          %option{value: ""} --
                      %span 日
                    %p.registration-all__content--text-gray
                      ※ 本人情報は正しく入力してください。会員登録後、修正するには
                      お時間を頂く場合があります。
                    = render "shared/recaptcha"
                    .registration-all__form-group
                      %p.registration-all__content--text-center
                        「次へ進む」のボタンを押すことにより、
                        = link_to "利用規約", "/", class: "registration-all__a"
                        に同意したものとみなします
                    %button.registration-all__btn-red{type: "submit"}
                      次へ進む
                    .registration-all__form-group
                      %p.text-right
                        = link_to "本人情報の登録について", "/", class: "registration-all__a"
                        %i.fas.fa-chevron-right


      / フッター部分
      = render 'shared/footer'