config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get "signup" => "devise/registrations#index", as: "signup_index"
    get "/signup/registration" => "devise/registrations#new", as: "signup_registration"
    get "/signup/confirmation" => "phonenumbers#new", as: "phonenumber_registration"
    get "/signup/address/:id" => "addresses#new", as: "address_new_registration"
    post "/signup/address/:id" => "addresses#create", as: "address_create_registration"
    get "/signup/credit/:id" => "credits#new", as: "credit_new_registration"
    post "/signup/credit/:id" => "credits#create", as: "credit_create_registration"
    get "/signup/complete" => "users/registrations#complete", as: "complete_registration"
  end
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: 'users/registrations',
    sessions: 'users/sessions'
   }
  root 'tops#index'
  resources :tops, only: [:index] do
    collection do
      get 'get_child_categories', defaults: { format: 'json' }
      get 'get_grandchild_categories', defaults: { format: 'json' }
    end
  end
  resources :phonenumbers, only: [:new, :create]
  resources :users, only: [:show] do
    resources :credits, only: [:index, :create]
    collection do
      get 'card'
      get 'identification'
      get 'logout'
      get 'profile'
    end
  end
  resources :exhibitions, only: [:index, :show]
  resources :items, except: [:index] do
    collection do
      get 'search'
      get 'get_children_categories', defaults: { format: 'json' }
      get 'get_grandchildren_categories', defaults: { format: 'json' }
    end
  end
  resources :purchases, only: [:show, :update]
end

app/views/shared/_footer.html.haml
%footer.new-user-top-footer
  %nav.new-user-top-nav
    %ul.new-user-top-nav__lists
      %li.new-user-top-nav__lists--list
        = link_to "プライバシーポリシー", "/", class: "new-user-top-nav__lists--list--link"

      %li.new-user-top-nav__lists--list
        = link_to "メルカリ利用規約", "/", class: "new-user-top-nav__lists--list--link"

      %li.new-user-top-nav__lists--list
        = link_to "特定商取引に関する表記", "/", class: "new-user-top-nav__lists--list--link"
        
  %a.new-user-top-footer__logo{ href: "#" }
    = image_tag "mercariLogoGray.svg", alt: "mercari", class: "new-user-top-footer__logo__img"
  
  %p.new-user-top-footer__under-logo
    %small © 2019 Mercari

app/views/shared/_header.html.haml
-# ヘッダー部分
%header.new-user-top-header
  %h1.new-user-top-header__logo
    = link_to "/", class: "new-user-top-header__logo__link" do
      = image_tag "mercariLogo.svg"

app/views/shared/_mypage-leftside.html.haml
.mypage-leftside
  .mypage-leftside__list
    %li
      = link_to user_path(current_user), class: "mypage-leftside__list__item" do
        マイページ
        %i.fa.fa-chevron-right
    %li
      = link_to "#", class: "mypage-leftside__list__item" do
        お知らせ
        %i.fa.fa-chevron-right
    %li
      = link_to "#", class: "mypage-leftside__list__item" do
        やることリスト
        %i.fa.fa-chevron-right
    %li
      = link_to "#", class: "mypage-leftside__list__item" do
        いいね！一覧
        %i.fa.fa-chevron-right
    %li
      = link_to new_item_path, class: "mypage-leftside__list__item" do
        出品する
        %i.fa.fa-chevron-right
    %li
      = link_to exhibitions_path, class: "mypage-leftside__list__item" do
        出品した商品 - 出品中
        %i.fa.fa-chevron-right
    %li
      = link_to "#", class: "mypage-leftside__list__item" do
        出品した商品 - 取引中
        %i.fa.fa-chevron-right
    %li
      = link_to "#", class: "mypage-leftside__list__item" do
        出品した商品 - 売却済み
        %i.fa.fa-chevron-right
    %li
      = link_to "#", class: "mypage-leftside__list__item" do
        購入した商品 - 取引中
        %i.fa.fa-chevron-right
    %li
      = link_to "#", class: "mypage-leftside__list__item" do
        購入した商品 - 過去の取引
        %i.fa.fa-chevron-right
    %li
      = link_to "#", class: "mypage-leftside__list__item" do      
        ニュース一覧
        %i.fa.fa-chevron-right
    %li
      = link_to "#", class: "mypage-leftside__list__item" do
        評価一覧
        %i.fa.fa-chevron-right
    %li
      = link_to "#", class: "mypage-leftside__list__item" do
        ガイド
        %i.fa.fa-chevron-right
    %li
      = link_to "#", class: "mypage-leftside__list__item" do
        お問い合わせ
        %i.fa.fa-chevron-right

  %h3.mypage-nav-head メルペイ
  %ul.mypage-leftside__list
    %li
      = link_to "#", class: "mypage-leftside__list__item" do
        売上・振込申請
        %i.fa.fa-chevron-right
    %li
      = link_to "#", class: "mypage-leftside__list__item" do
        ポイント
        %i.fa.fa-chevron-right
        
  %h3.mypage-nav-head 設定
  %ul.mypage-leftside__list
    %li
      = link_to profile_users_path, class: "mypage-leftside__list__item" do
        プロフィール
        %i.fa.fa-chevron-right
    %li
      = link_to "#", class: "mypage-leftside__list__item" do
        発送元・お届け先住所変更
        %i.fa.fa-chevron-right
    %li
      = link_to card_users_path, class: "mypage-leftside__list__item" do
        支払い方法
        %i.fa.fa-chevron-right
    %li
      = link_to "#", class: "mypage-leftside__list__item" do
        メール/パスワード
        %i.fa.fa-chevron-right
    %li
      = link_to identification_users_path, class: "mypage-leftside__list__item" do
        本人情報
        %i.fa.fa-chevron-right
    %li
      = link_to "#", class: "mypage-leftside__list__item" do
        電話番号の確認
        %i.fa.fa-chevron-right
    %li
      = link_to logout_users_path, class: "mypage-leftside__list__item" do
        ログアウト
        %i.fa.fa-chevron-right

app/views/shared/_pankuzu.html.haml
.pankuzu
  %ul
    %li
      = breadcrumbs separator: " &nbsp;&nbsp;&#62;&nbsp; "

app/views/shared/_recaptcha.html.haml
.registration-all__content
  .registration-all__form-group
    .g-recaptcha.signup-recaptcha
      %div.recaptcha-form
        %div
          %iframe.recaptcha-frame{frameborder: :"0",  name: :"a-mkmk6jkic1h2", role: :"presentation", sandbox: :"allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation", scrolling: :"no", src: :"https://www.google.com/recaptcha/api2/anchor?ar=1&k=6LfZGCYTAAAAAHoK-s7Lg5OdYg5Fq4susvALmZoc&co=aHR0cHM6Ly93d3cubWVyY2FyaS5jb206NDQz&hl=ja&v=v1563777128698&size=normal&cb=i3am7gn33cqe"}
          %textarea#g-recaptcha-response.g-recaptcha-response

app/views/shared/_sell-button.html.haml
= link_to new_item_path do
  %span.icon-sell-btn
    .icon-sell-btn__text
      出品
    %i.fa.fa-camera

app/views/shared/_top-footer.html.haml
.top-banner-wrapper
  .banner
    .banner__inner
      .banner__inner__background
      %h2 スマホでかんたんフリマアプリ
      %p 今すぐ無料ダウンロード！
      .banner__inner__icon.clearfix
        .banner__inner__icon--logo
          = image_tag "mercari_icon", alt: "logo", width: "68"
        %ul.clearfix
          %li
            = link_to "#" do
              = image_tag "app-store.svg", alt: "itunes", height: "40", width: "133", class: "apple"
          %li
            = link_to "#" do
              = image_tag "google-play.svg", alt: "google-play", height: "40", width: "133", class: "google"
    %figure
      = image_tag "download_content_pc.png", alt: "banner-image", width: "300"

%footer.top-footer
  %nav.top-footer-wrapper.clearfix
    .top-footer__cell
      %h2.top-footer__cell--head メルカリについて
      %ul
        %li
          = link_to "会社概要（運営会社）", "#"
        %li
          = link_to "採用情報", "#"
        %li
          = link_to "プレスリリース", "#"
        %li
          = link_to "公式ブログ", "#"
        %li
          = link_to "メルカリロゴ利用ガイドライン", "#"
        %li.top-footer__cell--social-link
          = link_to "#", target: "_blank" do
            %i.fab.fa-twitter
          = link_to "#", target: "_blank" do
            %i.fab.fa-facebook-square

    .top-footer__cell
      %h2.top-footer__cell--head ヘルプ＆ガイド
      %ul
        %li
          = link_to "メルカリガイド", "#"
        %li
          = link_to "らくらくメルカリ便", "#"
        %li
          = link_to "ゆうゆうメルカリ便", "#"
        %li
          = link_to "大型メルカリ便", "#"
        %li 
          = link_to "車体取引ガイド", "#"
        %li
          = link_to "メルカリあんしん・あんぜん宣言！", "#"
        %li
          = link_to " 偽ブランド品撲滅への取り組み", "#"
        %li
          = link_to "メルカリボックス", "#" 

    .top-footer__cell.full-width
      %h2.top-footer__cell--head プライバシーと利用規約
      .full-width__left
        %ul
          %li
            = link_to "プライバシーポリシー", "#"
          %li
            = link_to "メルカリ利用規約", "#"
          %li
            = link_to "あんしんスマホサポート制度に関する利用特約", "#"
          %li
            = link_to "コンプライアンスポリシー", "#"
      .full-width__right
        %ul
          %li
            = link_to "個人データの安全管理に係る基本方針", "#"
          %li
            = link_to "特定商取引に関する表記", "#"
          %li
            = link_to "資金決済法に基づく表示", "#"
          %li
            = link_to "法令順守と犯罪抑止のために", "#"

    .top-footer__cell.footer-nation
      %h2.top-footer__cell--head 国
      %ul
        %li
          = link_to "日本", "#"
        %li
          = link_to "United States", "#"
  
  .top-footer__bottom
    .top-footer__bottom--logo
      = link_to "#" do
        = image_tag "logo-white", alt: "mercari", height: "33", width: "124"
    %span.top-footer__bottom--copyright
      %small © 2019 Mercari

app/views/shared/_top-header.html.haml
.top-header
  .top-header__inner
    .top-header__inner__top
      %h1
        = link_to root_path do
          = image_tag "top-logo.svg", alt: "mercari", height: "36", width: "134"
      = form_with url: search_items_path, local: true, method: :get, class: "top-header__inner__top--form" do |f|
        = f.text_field :search, class: "input-default", placeholder: "何かお探しですか？", type: "search", value: ""
        = f.button type: "submit", class: 'top-header__inner__top--form__label__submit' do
          %i.fas.fa-search.fa-lg
    .top-header__inner__nav.clearfix
      %nav.top-navbar-left
        %ul.top-navbar-left__wrapper
          %li.category-select
            %h2
              .top-navbar-left__wrapper--list__category
                = link_to "#" do
                  %i.fas.fa-bars
                  %span カテゴリーから探す
              .top-navbar-left__category.category-select
                .top-navbar-left__category__parent.category-select
                  - @parent_categories.each do |category|
                    %li.parent-category-list{"data-category-id": "#{category.id}"}
                      %h2
                        = category.name
                  %li.parent-category-list
                    %h2 カテゴリー一覧
                .top-navbar-left__category__kodomotachi
                  .top-navbar-left__category__kodomotachi__children.category-select
                  .top-navbar-left__category__kodomotachi__grandchildren.category-select
          %li
            %h2
              .top-navbar-left__wrapper--list__brand
                = link_to "#" do
                  %i.fas.fa-tag
                  %span ブランドから探す
              .top-navbar-left__brand
                %li.brand-list
                  %h2 シャネル
                %li.brand-list
                  %h2 ナイキ
                %li.brand-list
                  %h2 ルイ ヴィトン
                %li.brand-list
                  %h2 シュプリーム
                %li.brand-list
                  %h2 アディダス
                %li.brand-list
                  %h2 ブランド一覧
      .top-navbar-right
        - if user_signed_in?
          %ul
            %li
              %i.fa.fa-bell
            %li
              .top-navbar-right__notice お知らせ
            %li
              %i.fa.fa-check
            %li
              .top-navbar-right__todolist やることリスト
            %li
              = image_tag "ikedayuka.jpg", size: '32x32', class: "mypage_image"
            %li
              = link_to "マイページ", "/users/#{current_user.id}", class: "top-navbar-right__mypage"
        - else
          %ul
            %li
              = link_to "新規会員登録", signup_index_path, class: "top-navbar-right__registration btn-red"
            %li
              = link_to "ログイン", new_user_session_path, class: "top-navbar-right__login nav-btn"