config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get "signup" => "devise/registrations#index", as: "signup_index"
    get "/signup/registration" => "devise/registrations#new", as: "signup_registration"
    get "/signup/confirmation" => "phonenumbers#new", as: "phonenumber_registration"
    get "/signup/address/:id" => "addresses#new", as: "address_new_registration"
    post "/signup/address/:id" => "addresses#create", as: "address_create_registration"
    get "/signup/credit/:id" => "credits#new", as: "credit_new_registration"
    post "/signup/credit/:id" => "credits#create", as: "credit_create_registration"
    get "/signup/complete" => "users/registrations#complete", as: "complete_registration"
  end
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: 'users/registrations',
    sessions: 'users/sessions'
   }
  root 'tops#index'
  resources :tops, only: [:index] do
    collection do
      get 'get_child_categories', defaults: { format: 'json' }
      get 'get_grandchild_categories', defaults: { format: 'json' }
    end
  end
  resources :phonenumbers, only: [:new, :create]
  resources :users, only: [:show] do
    resources :credits, only: [:index, :create]
    collection do
      get 'card'
      get 'identification'
      get 'logout'
      get 'profile'
    end
  end
  resources :exhibitions, only: [:index, :show]
  resources :items, except: [:index] do
    collection do
      get 'search'
      get 'get_children_categories', defaults: { format: 'json' }
      get 'get_grandchildren_categories', defaults: { format: 'json' }
    end
  end
  resources :purchases, only: [:show, :update]
end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :user, optional: true
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  
  def index

  end

  def new
    
  end

  def create
    Payjp.api_key = ENV["PAYJP_SECRET_ACCESS_KEY"]
    customer = Payjp::Customer.create(card: params[:payjpToken])
    @credit = Credit.new(user_id: current_user.id, card_token: params[:payjpToken], customer_id: customer.id)
    if @credit.save
      redirect_to root_path, notice: "カードの作成が完了しました"
    else
      render :index
    end
  end

end

app/views/credits/index.html.haml
.mainbody
  = render "shared/top-header"
  - breadcrumb :addCard
  = render 'shared/pankuzu'
  .mainbody__main
    .mainbody__content
      %section.mainbody__container
        %h2.mainbody__chapter-head クレジットカード情報入力
        = form_tag("/users/#{current_user.id}/credits", method: :post, class: "mainbody__inner-registration", id: "change-form") do
          .mainbody__inner-registration__single-content
            .mainbody__form-group
              %label.mainbody__form-group--label カード番号
              %span.mainbody__require 必須
              %input.mainbody__form-group--input-default.number{id: "payment_card_no", maxlegth: "16", name: "number", placeholder: "半角数字のみ", type: "text"}/

              %ul.mainbody__cards
                %li.mainbody__cards--card
                  = image_tag "visa.png"
                %li.mainbody__cards--card
                  = image_tag "mastercard.png"
                %li.mainbody__cards--card
                  = image_tag "saison-card.png"
                %li.mainbody__cards--card
                  = image_tag "jcb.png"
                %li.mainbody__cards--card
                  = image_tag "american_express.png"
                %li.mainbody__cards--card
                  = image_tag "dinersclub.png"
                %li.mainbody__cards--card
                  = image_tag "discover.png"

            .mainbody__form-expire
              %div
                %label.mainbody__form-group--label 有効期限
                %span.mainbody__require 必須
              .mainbody__form-expire__half
                %select.mainbody__form-expire__half--default.exp_month{id: "payment_card_expire_mm", type: "text", name: "exp_month"}
                  %option{value: :"1"} 01
                  %option{value: :"2"} 02
                  %option{value: :"3"} 03
                  %option{value: :"4"} 04
                  %option{value: :"5"} 05
                  %option{value: :"6"} 06
                  %option{value: :"7"} 07
                  %option{value: :"8"} 08
                  %option{value: :"9"} 09
                  %option{value: :"10"} 10
                  %option{value: :"11"} 11
                  %option{value: :"12"} 12
                %span.month 月
              .mainbody__form-expire__half
                %select.mainbody__form-expire__half--default.exp_year{type: "text", id: "payment_card_expire_yy", name: "exp_year"}
                  %option{value: :"2019"} 19
                  %option{value: :"2020"} 20
                  %option{value: :"2021"} 21
                  %option{value: :"2022"} 22
                  %option{value: :"2023"} 23
                  %option{value: :"2024"} 24
                  %option{value: :"2025"} 25
                  %option{value: :"2026"} 26
                  %option{value: :"2027"} 27
                  %option{value: :"2028"} 28
                  %option{value: :"2029"} 29
                %span.year 年

            .mainbody__form-group-under
              %label.mainbody__form-group--label セキュリティコード
              %span.mainbody__require 必須
              %input.mainbody__form-group--input-default.cvc{id: "payment_card_security_code",maxlength: "4", name: "cvc", placeholder: "カード背面4桁もしくは3桁の番号", type: "text"}/

            .mainbody__seqcode
              .mainbody__seqcode-text
                カード裏面の番号とは？
            %input.registration-all__btn-red.submit{type: :submit, id: "submit-button", value: "追加する"}
            %p#result
            %input.payjp-token{ type: "hidden", name: "payjpToken", value: "" }

    = render 'shared/mypage-leftside'
    .mainbody__main__side
  = render "shared/top-footer"
  = render "shared/sell-button"

app/views/credits/new.html.haml
.registration-html
  .registration-body
    .registration-all
      .registration-all__container
        / ヘッダー部分
        %header.registration-all__header
          %h1.registration-all__header--h1
            = link_to "/", class: "registration-all__header--a" do
              = image_tag "mercari2.png"
          %nav.registration-all__bar
            %ol.registration-all__bar--ol
              %li.registration-all__bar--through
                会員情報
                .progress-status
              %li.registration-all__bar--through-through
                電話番号認証
                .progress-status
              %li.registration-all__bar--through-through
                お届け先住所入力
                .progress-status
              %li.registration-all__bar--active
                支払い方法
                .progress-status
              %li.registration-all__bar--last
                完了
                .progress-status
        / メイン部分
        %main.registration-all__main
          %section.registration-all__main-container
            %h2.registration-all__chapter-head 支払い方法
            -# = form_with url: complete_registration_path, method: :get, local: true do |f|
            %form.registration-all__inner{:action => "/signup/complete"}
              .registration-all__content
                .registration-all__form-group
                  %label.registration-all__form-group--label{:for => "card-num"} カード番号
                  %span.registration-all__require 必須
                  %input.input-default{:placeholder => "半角数字のみ", :type => "text"}/
                  %ul.registration-all__cards
                    %li.registration-all__cards--card
                      = image_tag "visa.png"
                    %li.registration-all__cards--card
                      = image_tag "mastercard.png"
                    %li.registration-all__cards--card
                      = image_tag "saison-card.png"
                    %li.registration-all__cards--card
                      = image_tag "jcb.png"
                    %li.registration-all__cards--card
                      = image_tag "american_express.png"
                    %li.registration-all__cards--card
                      = image_tag "dinersclub.png"
                    %li.registration-all__cards--card
                      = image_tag "discover.png"

                .registration-all__form-group
                  %div
                    %label.registration-all__form-group--label 有効期限
                    %span.registration-all__require 必須
                  %select.input-default.half.card
                    %option{:value => "1"} 01
                    %option{:value => "2"} 02
                    %option{:value => "3"} 03
                    %option{:value => "4"} 04
                    %option{:value => "5"} 05
                    %option{:value => "6"} 06
                    %option{:value => "7"} 07
                    %option{:value => "8"} 08
                    %option{:value => "9"} 09
                    %option{:value => "10"} 10
                    %option{:value => "11"} 11
                    %option{:value => "12"} 12
                  %span.month 月
                  %select.input-default.half.card
                    - for i in 19..29
                      %option{:value => "#{i}"} #{i}
                  %span.year 年
                .registration-all__form-group
                  %label.registration-all__form-group--label{:for => "code"} セキュリティコード
                  %span.registration-all__require 必須
                  %input.input-default{:placeholder => "カード背面4桁もしくは3桁の番号"}/
                .registration-all__form-group
                  %p.text-right
                    = link_to "カード裏面の番号とは？", "/", class: "registration-all__a"
                    %i.fas.fa-chevron-right
                %button.registration-all__btn-red{:type => "submit"}
                  次へ進む

        / フッター部分
        = render 'shared/footer'